root:         ./root
redirects:
  help: https://github.com/chatie/wechaty/issues
  faq: ./faq.md
gitbook:      ">= 3.0.0"
title:        "Chatie Documentations"
description:  "Tutorials, API, and Support."
author:       "Huan LI <zixia@zixia.net>"
links: 
  - 
    sidebar: 
      - 
        Home: "https://www.chatie.io"
